const ActionType = {
	USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
	USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
	USER_LOGOUT: 'USER_LOGOUT',
	USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST'
};

export default ActionTypes;